### ISSUE TITLE
intermittent test failures

### ISSUE THREAD

**Issue by T045T** [RobotWebTools/rosbridge_suite#132]
The [Travis build](https://travis-ci.org/RobotWebTools/rosbridge_suite/builds/37283763#L2032) for #131  failed, while [this one](https://travis-ci.org/T045T/rosbridge_suite/builds/37283023) (same commit, but on my fork) succeeded.
I also think I saw #127 failing yesterday, but not today.

Lastly, [this build](https://travis-ci.org/RobotWebTools/rosbridge_suite/builds/26859495) broke, while [this one](https://travis-ci.org/RobotWebTools/rosbridge_suite/builds/26852654) (again, same commit).

The throttling tests especially give inconsistent results, probably because they're timing-sensitive.
We saw in https://github.com/RobotWebTools/roslibjs/issues/114 that Travis brings out the worst in that kind of situation...

**Comment by rctoris** [comment]
Is this still happening?

**Comment by jihoonl** [comment]
travis build is fine now.
