### ISSUE TITLE
Define spec for TCP transport

### ISSUE THREAD

**Issue by T045T** [RobotWebTools/rosbridge_suite#140]
RobotWebTools/roslibjs#126 illustrates the need to document the TCP transport some more.

Currently, `rosbridge` seems to _mostly_ send one JSON message at a time, but not always, which leads to parsing errors on the `roslibjs` side.

[This](http://stackoverflow.com/questions/6573870/choice-of-transports-for-json-over-tcp) StackOverflow post discusses some possible approaches. 

They boil down to either:
- newline-separated messages, with no newlines _inside_ each JSON message (or potentially **very** slow parsing as the parser tries to parse an increasing number of lines) or
- sending the JSON message's size before the actual message.

**Comment by mitchellwills** [comment]
Has any process been made on this? In my mind sending the message size would be the best approach.
