### ISSUE TITLE
Websocket handler and Nagle's algorithm

### ISSUE THREAD

**Issue by smamessier** [RobotWebTools/rosbridge_suite#171]
Using rosbridge Websocket and roslibjs, I subscribe to a 60 Hz Ros message at a 15 ms throttle rate with 0 queue size, I end up receiving 6 messages at a time but every 100 ms.

It took me some time but I tracked this lag down to Nagle's algorithm that gathers tcp messages together before sending when small and sent at a high frequency. 
This way, low throttle rate (typically under 50 ms) are only respected in average and this is a huge problem when you want some decent head tracking for instance.
 
Using Tornado WebSocketHandler API, I tried tu use self.set_nodelay(True) which is supposed to deactivate Nagle. I'm behind a corporate proxy so that might be why (Still the same message scheduling pattern maybe caused by proxy's nagle)

I only found a kludgy way of achieving 15 ms between each message by forcing Roslibjs to ping back the websocket server on each message reception (this forces Nagle's algorithm to flush). Idea come from this post 
http://stackoverflow.com/questions/13373519/websocket-tcp-packets-clumping-together/13406438#13406438

But the best solution should be to have an option maybe in WebSocket.launch to enable/disable Nagle.

**Comment by smamessier** [comment]
I had the opportunity to test without a proxy, and adding 
    self.set_nodelay(True)
in rosbridge_websocket.py  line 63 (opening connection callback), fixes the issue. This should either be added or available as an option.

**Comment by jihoonl** [comment]
@smamessier Would you create a PR for your patch?

**Comment by smamessier** [comment]
Ok, I created a PR here #175

**Comment by T045T** [comment]
Closed via #175
