### ISSUE TITLE
How to use rosbridge in Java?

### ISSUE THREAD

**Issue by paive** [RobotWebTools/rosbridge_suite#213]
I want to write the program which need to communicate with nodes of ROS in Java, however I could not find the related tutorial, can anyone tell me how to use rosbridge in java  thanks for everyone`s help!

**Comment by rctoris** [comment]
You can launch rosbridge_websocket.launch and use jrosbridge as a client-side library to talk to ROS: https://github.com/GT-RAIL/jrosbridge
