### ISSUE TITLE
rosbridge_server with udp

### ISSUE THREAD

**Issue by salsalam** [RobotWebTools/rosbridge_suite#215]
I noticed a udp launch file in the develop branch.  I don't have this in my installation.

We are developing a remote joystick control for a robot and the network interface will be wireless, therefore we'd like to use udp as a transport.

Is it safe to download the source, build and use this???  It looks like we have rosbridge_library 7.13 installed.  We are using ubuntu 14.04 and python 2.7.

Thanks

**Comment by rctoris** [comment]
Yes, the UDP version should be fine to use although it has not been tested as much.
