### ISSUE TITLE
sudo apt-get install ros-indigo-rosbridge-server grabs 0.7.13

### ISSUE THREAD

**Issue by salsalam** [RobotWebTools/rosbridge_suite#216]
I'm a little new to ubuntu.  When I run sudo apt-get install ros-indigo-rosbridge-server it installs version 0.7.13 (january 11, 2016).  I noticed that there is a 0.7.14 in master which includes a udp version.

When can i install this?  Should I download a zip??  I guess it's all in python, so there is no build involved...

Thanks for your help

**Comment by rctoris** [comment]
ROS is in charge of syncing new releases into Ubuntu. See http://repositories.ros.org/status_page/ros_indigo_default.html
