### ISSUE TITLE
Can we have a todo-list for compatibility with kinetic ? 

### ISSUE THREAD

**Issue by Kiloreux** [RobotWebTools/rosbridge_suite#220]
That's a question, can we please make a todo-list for all the changes  that need to be implemented in order for kinetic compatibility ?

**Comment by rctoris** [comment]
I'm not sure there are any changes given http://wiki.ros.org/kinetic/Migration

It's a question of testing and making sure the necessary upstream repos are in (which they should be). I have no migrated to kinetic so I have not done any testing.

**Comment by Kiloreux** [comment]
Cool, I will update this issue once I do the testing over the new kinetic with required changes.

**Comment by jihoonl** [comment]
:+1:

**Comment by cberner** [comment]
Looks like Kinetic was released today. Any update on this? Would it be helpful for me to do some testing?

**Comment by dcconner** [comment]
Since it is not released, I built from source under kinetic.
I had to also build rosauth  as it is not released as package either, and needed to manually install python-bson, but otherwise it appeared to work for my code without modification.

**Comment by Kiloreux** [comment]
@dcconner did you run all the tests ?

**Comment by dcconner** [comment]
No just my use case.  Just providing a data point for others that want to
try

On Friday, June 3, 2016, kiloreux <notifications@github.com> wrote:

> @dcconner <https://github.com/dcconner> did you run all the tests ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/RobotWebTools/rosbridge_suite/issues/220#issuecomment-223712247>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAECz57FDL7pUlYJaBnT93_R6_v8eDcnks5qIK5hgaJpZM4IQQ5s>
> .
>


-- 
Best regards,

David C. Conner, PhD
Assistant Professor
Department of Physics, Computer Science and Engineering
Christopher Newport University
329 Luter Hall
1 Avenue of the Arts, Newport News, VA, 23606, USA
david.conner@cnu.edu
(757) 594-7360

**Comment by dcconner** [comment]
I ran "rostest rosbridge_library test_all.test"

105 tests success; 0 errors; 0 failures

**Comment by Kiloreux** [comment]
@dcconner , Thank you, closing issue for now.
