### ISSUE TITLE
sudo apt-get upgrade get 7.14 but no UDP Launch file

### ISSUE THREAD

**Issue by salsalam** [RobotWebTools/rosbridge_suite#225]
I noticed that sudo apt-get upgrade installed a new version of rosbridge_suite, 7.14, but the launch directory doesn't contain an option to launch the UDP capability.

Is there something I'm missing?

Thanks

**Comment by jihoonl** [comment]
It was missing in the CMakelists.txt configuration. I will add it in next release.
