### ISSUE TITLE
Options for unreliable transport?

### ISSUE THREAD

**Issue by ablakey** [RobotWebTools/rosbridge_suite#235]
I'm struggling with cases where high bandwidth topics such as lidar scans begin to back up in the pipe due to network connectivity issues (eg. wifi gets bad for a while).  The result is that my interface renders old data, and in some bad cases, never catches up.

As far as I understand, this is a property of TCP -> Websockets. 

How do others deal with this case?  Is there an opportunity for a form of unreliable transport to be configurable?  I dunno if we have control of how large the transport buffer is and when to drop data? I suspect that's well below the application layer...

**Comment by jihoonl** [comment]
[rosbridge_udp](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosbridge_server/launch/rosbridge_udp.launch) would work to support unreliable network.
