### ISSUE TITLE
Using rosbridge for an Android Application

### ISSUE THREAD

**Issue by SNBasti** [RobotWebTools/rosbridge_suite#237]
I want to use the java rosbridge client for my android application but I am running into problems:
http://stackoverflow.com/questions/39235300/porting-javarosbridge-to-android

Is there any workaround or common approach to deploy jrosbridge @ android? 
Do I have to implement the websockets on my own? 

Thanks in advance. Cheers.

**Comment by jihoonl** [comment]
Please post questions on ros answers next time.  It looks like you found the answer [here](https://github.com/rctoris/jrosbridge/issues/19) :)
