### ISSUE TITLE
Can't connect to move_base server if rosbridge_websocket.launch launched

### ISSUE THREAD

**Issue by sonictl** [RobotWebTools/rosbridge_suite#251]
# SimpleActionClient Can't connect to move_base server if rosbridge_websocket.launch launched.
1. $ sudo apt-get install ros-inidigo-rosbridge-server
2. $ roslaunch rosbridge_server rosbridge_websocket.launch port:=8080
3. $ ./my_node.py

code for my_node.py:

```
 self.moveClient = actionlib.SimpleActionClient("move_base", MoveBaseAction)
 self.moveClient.wait_for_server(rospy.Duration(60))  #Can't connect to server, program will wait at here for 60 secs.
 self.goal = MoveBaseGoal()
 ... #envalue the self.goal
 self.moveClient.send_goal(self.goal)  #This will not work. robot doesn't move.
```

============
if I start the my_node.py before launch the rosbridge_websocket.launch, everything will be ok.
Thank you!!

**Comment by vinnu0428** [comment]
i have written a simple subscriber topic using this jar file. and it is working in the eclipse. but i was trying to run it in terminal. then it is waiting for connection with the server and it is not executing the code. do i need to add anything in the classpath . give me the dependencies list? reply ASAP. Thanks
