### ISSUE TITLE
Rosbridge can crash if WLAN is lost at unfortunate point in time

### ISSUE THREAD

**Issue by lenhartd** [RobotWebTools/rosbridge_suite#255]
Hi,

I am using 0.18.0 via npm. There is a rare but critical issue where rosbridge will crash if the wireless connection is lost at an unfortunate point in time.

```
/**
 * Registers as a publisher for the topic.
 */
Topic.prototype.advertise = function() {
  if (this.isAdvertised) {
    return;
  }
  this.advertiseId = 'advertise:' + this.name + ':' + (++this.ros.idCounter); <----
  this.ros.callOnConnection({ <----
    op: 'advertise',
    id: this.advertiseId,
    type: this.messageType,
    topic: this.name,
    latch: this.latch,
    queue_size: this.queue_size
  });
  this.isAdvertised = true;
};
```

If the wireless connection to the robot is dropped before advertise is called,
`this.ros`
will be null, causing the bridge to crash and bring down the service.

```
/usr/src/app/node_modules/roslib/src/core/Topic.js:119
this.advertiseId = 'advertise:' + this.name + ':' + (++this.ros.idCounter);
^

TypeError: Cannot read property 'idCounter' of null
at Topic.advertise (/usr/src/app/node_modules/roslib/src/core/Topic.js:119:66)
at Topic.publish (/usr/src/app/node_modules/roslib/src/core/Topic.js:154:10)
at Bridge._pubMessage (/usr/src/app/server/bridge/bridge.js:853:14)
at Bridge._keepAlive_loop (/usr/src/app/server/bridge/bridge.js:597:14)
at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by T045T** [comment]
The code snippets are from [roslibjs](https://github.com/RobotWebTools/roslibjs), but you're saying rosbridge crashes. Is that the case, or is it your node application (using roslibjs) that crashes?
If it's the latter, can you please open another issue in that project? :)

That said, ```this.ros```shouldn't be set to null automatically. Can you share more details about your setup?
