### ISSUE TITLE
Glob filter logic not working with last kinetic binaries

### ISSUE THREAD

**Issue by doisyg** [RobotWebTools/rosbridge_suite#256]
Hi,
First, thank you for the great work behind rosbridge. 
We would like to use the glob filter logic for security reason (having remote access to all rostopic/param/service can be a bit dangerous). With the current kinetic repo (0.7.16-0xenial-20161026-195828-0700), it is not working, though with the last source, it is.
Can someone push in the repo the last version? It would simplify installation and deployment on our side.
Thanks

**Comment by jihoonl** [comment]
https://github.com/RobotWebTools/rosbridge_suite/issues/250
https://github.com/ros/rosdistro/pull/13712

I just did. It should be available with next cycle

**Comment by doisyg** [comment]
thanks a lot
