### ISSUE TITLE
UDP Server :  RosbridgeUdpSocket instance has no attribute 'set_nodelay'

### ISSUE THREAD

**Issue by Tutorgaming** [RobotWebTools/rosbridge_suite#266]
After I launched the rosbridge_udp.launch and make some connection, it showed: 

> Unable to accept the incoming connection.  Reason: RosbridgeUdpSocket instance has no attribute 'set_nodelay'

So,  i go to ./src/rosbridge_server/udp_handler.py  and remove line 47 .
After that, it didn't show up any warning and show client count perfectly.

Is that line have any effect on the whole Node?

**Comment by orac** [comment]
This seems to be fixed by 4a7f2d3b0e24bc323a70dcbb60fe81f82296f074

**Comment by jihoonl** [comment]
Ok thanks
