### ISSUE TITLE
How do I parse the LaserScan data JS obtained?

### ISSUE THREAD

**Issue by yghcats** [RobotWebTools/rosbridge_suite#288]
How do I parse the LaserScan data JS obtained?

server data ：header: 
  seq: 101732
  stamp: 
    secs: 1487324446
    nsecs: 379890600
  frame_id: laser
angle_min: -3.12413907051
angle_max: 3.14159274101
angle_increment: 0.0174532923847
time_increment: 1.55012827463e-07
scan_time: 5.56496015633e-05
range_min: 0.15000000596
range_max: 8.0
ranges: [ inf, 0.7260000109672546, 0.7480000257492065, inf, 0.7749999761581421, inf, 0.7950000166893005, inf, 0.8240000009536743, 0.8500000238418579, inf, 0.8830000162124634, inf, 0.8759999871253967, 0.8539999723434448]
intensities: [ 0.0, 0.0, 0.0, 0.0, 0.0, 47.0, 0.0, 0.0, 0.0, 47.0, 0.0, 47.0, 47.0, 0.0, 47.0, 0.0, 47.0, 47.0, 0.0, 0.0, 0.0, 47.0, 47.0, 0.0, 0.0, 47.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 47.0, 0.0]

**Comment by jihoonl** [comment]
what do you mean? at the javascript level? can you elaborate what exactly you want to do?

**Comment by yghcats** [comment]
@jihoonl 
I want to display the acquired slam data in this example：http://robotwebtools.org/demos/map.html
Display a map

**Comment by jihoonl** [comment]
You can use [ROS3D.LaserScan](https://github.com/RobotWebTools/ros3djs/blob/develop/src/sensors/LaserScan.js) to visualize laser scan in 3dviewer.
