### ISSUE TITLE
Plans for webrtc implementation?

### ISSUE THREAD

**Issue by doisyg** [RobotWebTools/rosbridge_suite#293]
Hi,
Webrtc, and more specifically webrtc datachannels seem to be the next logical evolution for the transport layer of rosbridge. It could permit remote ros access over the web without any firewall configuration or port forwarding.
I am aware of https://github.com/MayfieldRoboticsPublic/ros-webrtc but it seems focuses on videos, use an old version of webrtc and I could not get it to work.
Is there any current effort in this direction?

**Comment by jihoonl** [comment]
Afaik, there is no further development in this direction.
