### ISSUE TITLE
Consider making UNREGISTER_TIMEOUT configurable

### ISSUE THREAD

**Issue by jorgenfb** [RobotWebTools/rosbridge_suite#320]
Pull request #247 introduces a  10 second delay to mitigate issue #138. I propose making this property configurable through parameters. I can provide a PR if we decide it is a good idea.

The reason I want to configure the timeout is that we still see the problem described in #138 at rare occasions and would experiment with other timeouts. I also see forks completely disabling the unregistering from a topic to prevent these problems. Even if you don't agree with their solution, making the timeout configurable would probably allow them to run the official version with a really high timeout value, removing the need to maintain a fork.

**Comment by jihoonl** [comment]
Hi @jorgenfb, sounds good! Could you provide a PR?
