### ISSUE TITLE
How to decode png compressed message? Any example code?

### ISSUE THREAD

**Issue by wfcola** [RobotWebTools/rosbridge_suite#325]
I have confused with the png encode compressed message that the string after compressed is stand for the original message or the data in original message only?
When i need to decode the compressed message, any introductinos can help me out?

**Comment by Behery** [comment]
Hi @wfcola 
Do you mean sensor_msgs/CompressedImage?
did you try http://wiki.ros.org/rospy_tutorials/Tutorials/WritingImagePublisherSubscriber? if not, can you provide more details of what you are trying to do?

**Comment by wfcola** [comment]
THX @Behery 
I try to use the protocol while subscribe the map message through web. However the map message would become very large sometime and I noticed that the compression argument is followed with the subscribe protocol.  
I tried to subscribe the map message with compression of "png" and i got a very long string.
So how do i decode this string to original message? Are there any example codes or directions?
Following is the Protocol I try to use.
https://github.com/RobotWebTools/rosbridge_suite/blob/develop/ROSBRIDGE_PROTOCOL.md

**Comment by Behery** [comment]
Hi again @wfcola sorry for the late response. I haven't really tried this before tbh, but try using [pngcompression.decode](https://github.com/RobotWebTools/rosbridge_suite/blob/4b98dc71a396c5c2074005c25036647702902366/rosbridge_library/src/rosbridge_library/internal/pngcompression.py#L54) I think it's what's your looking for.

**Comment by Behery** [comment]
Hi @wfcola 
I haven't really tried this before tbh, but take a look at the [pngconpression](https://github.com/RobotWebTools/rosbridge_suite/blob/b0945dd34ca16f293cff3d430fea11eecd93f82b/rosbridge_library/src/rosbridge_library/internal/pngcompression.py) module, depending on the language you're using you to interact with rosbridge, use something that does a similar decompression. I hope this helps :)

**Comment by RalphCodesTheInternet** [comment]
Did you solve the problem? I am using roslibjs and have been struggling for days to decode a PNG mesage. 
Not even the decompressPNG code in the library is working
