### ISSUE TITLE
Slight mistakes in Rosbridge specification?

### ISSUE THREAD

**Issue by ppianpak** [RobotWebTools/rosbridge_suite#328]
I've been working in a C++ client library to connect to Rosbridge [https://github.com/ppianpak/rosbridgecpp](https://github.com/ppianpak/rosbridgecpp) and I think I found slight mistakes in the specification.

1. <list< json>> in Call Service and Service Response should just be < json>. I tried sending a list of json (i.e. [{}, {}, ...] and it gave me errors, but sending a json object works fine.

2. "id" and "values" are not optional. They need to be send even though they might be blank (i.e. "id": "", "values": {}). Note that id also needs to match the id from call_service for the message to get return to the service caller.

I might be wrong, but these were what happened to me.

**Comment by abarger-bss** [comment]
I am also confused by this. Service calls in [roslibjs](https://github.com/RobotWebTools/roslibjs/blob/develop/src/core/Service.js#L63) service calls also appear to treat args and values as objects, not arrays. Are these libraries violating the spec?
