### ISSUE TITLE
ROSAPI: the *glob parameters does not work

### ISSUE THREAD

**Issue by krixkrix** [RobotWebTools/rosbridge_suite#331]
Here is my test:

 1. Launching some of my own ros nodes 
 2. Doing `rostopic list` reveals a long list of topics
 3. Launching `rosapi` with a launch file that sets the topics_glob param, intented to only let `/rosout` through.

The console output confirms that the topics_glob is set as expected:

>     SUMMARY
>     ========
>     
>     PARAMETERS
>      * /rosapi/params_glob: [*]
>      * /rosapi/services_glob: [*]
>      * /rosapi/topics_glob: [/rosout]
>      * /rosdistro: kinetic
>      * /rosversion: 1.12.13

But when I then do `rosservice call /rosapi/topics`, all existing topics are listed, incl /rosout.
I expected to see only the /rosout listed due to the topics_glob.

Are my expectations wrong?
What is the right use of the `*_glob` parameters?

**Comment by Affonso-Gui** [comment]
Was having the same problem.

This apparently is solved in commit https://github.com/RobotWebTools/rosbridge_suite/commit/111959495762d4dec8a59f27ddfe4cf8f09b8ff3 , so if you build and run from source it should be alright.
