### ISSUE TITLE
Release date for ROS Melodic

### ISSUE THREAD

**Issue by nlynn12** [RobotWebTools/rosbridge_suite#333]
What’s the release date for the rosbrigde server on Ubuntu 18.04 (ROS Melodic)?

**Comment by cberner** [comment]
Just wanted to add that I tried running all the tests on 18.04 and they passed

**Comment by ramezanifar** [comment]
Can you please release the rosbridge_suit for ROS Melodic?

**Comment by jihoonl** [comment]
[rosauth](https://github.com/GT-RAIL/rosauth) is not being released in order to release rosbridge in melodic.

@rctoris Can you release rosauth?

**Comment by flynneva** [comment]
....waiting on this too.  Any ideas when this will be released?

**Comment by pjreed** [comment]
rosauth has been released (https://github.com/ros/rosdistro/pull/18413), so this should be clear to go now.

**Comment by jihoonl** [comment]
https://github.com/ros/rosdistro/pull/18488

**Comment by ramezanifar** [comment]
Hi
In Ubuntu 18.04

sudo apt-get install ros-melodic-rosbridge-server

results in

E: Unable to locate package ros-melodic-rosbridge-server


Does that mean something was not completed in the release?
Thank you in advance

**Comment by jihoonl** [comment]
http://repositories.ros.org/status_page/melodic_default.html?q=rosbridge

It should have been released. Did you apt-get update?

**Comment by ramezanifar** [comment]
Hello Jihoon
My problem is fixed.
Thank you for your help
Regards
