### ISSUE TITLE
building a new widget - click-on map

### ISSUE THREAD

**Issue by vannem95** [RobotWebTools/rosbridge_suite#335]
Is it possible to build a widget of my own?

If so, is it possible to build a widget in which the user can select a point on a map and a certain service is called?

Thanks in advance

**Comment by mvollrath** [comment]
This does not seem to be an issue in Rosbridge, I would look into [Leaflet](https://leafletjs.com/) and [roslib](https://github.com/RobotWebTools/roslibjs) libraries to create what you are describing.
