### ISSUE TITLE
IOLoop add_callback never fires, Tornado 5.x and Py3 issue?

### ISSUE THREAD

**Issue by klintan** [RobotWebTools/rosbridge_suite#339]
Hey,
So I've been trying to get rosbridge_suite running on Py3, Mac High Sierra and ROS Melodic. Been a bit of a struggle, but I'm almost there. 

I identified an issue where the callback for sending a message to the client never fires, this line
`IOLoop.instance().add_callback(callback=partial(self.write_message, message, binary))` 
in the `websocket_handler.py` in rosbridge_server package.

Calling `self.write_message(message, binary)` works fine, and I've tried some stuff but haven't really gotten any closer to the solution. I'm running Tornado 5.x and Py3 which might be the culprit, 
any ideas on how to make this async? 

In addition I also had to add:
```
# Installing this policy allows event loops to be created automatically on any thread,
# matching the behavior of Tornado versions prior to 5.0 (or 5.0 on Python 2).
asyncio.set_event_loop_policy(AnyThreadEventLoopPolicy())
```
in the `open` function of the `websocket_handler.py` to fix a event loop/threading issue (no event loop in thread), which could of course also have unintended side-effects.

Many thanks,

**Comment by mvollrath** [comment]
I recommend using Tornado 4.5.3, as we do not support Tornado 5 yet.  If you get rosbridge working on Tornado 5, let us know how or send us a PR.
