### ISSUE TITLE
message_conversion.py does not correctly handle empty String vectors?

### ISSUE THREAD

**Issue by schornakj** [RobotWebTools/rosbridge_suite#340]
I have a project where I'm generating JSON from ROS message descriptions to initialize a 3rd-party messaging system. Message descriptions containing String vectors aren't converted to JSON correctly because the method detects an empty list when processing the field for the String vector and exits early before assigning a data type for the contents of the list (L161 below):
https://github.com/RobotWebTools/rosbridge_suite/blob/21868a3732a400e39d39cbd29c9f9b60f2e21a49/rosbridge_library/src/rosbridge_library/internal/message_conversion.py#L159-L172

I wanted to check if this was the desired behavior, and if changing the handling of empty lists would have undesirable side effects.

**Comment by mvollrath** [comment]
Looks like a bug, seems like the "duck out" logic needs improvement.
