### ISSUE TITLE
After tornado upgraded to version 5.0, websocket disconnects immediately after connection

### ISSUE THREAD

**Issue by zczcmlml** [RobotWebTools/rosbridge_suite#353]

**Comment by florian-leblanc** [comment]
Thanks for your help man i didn't know why it doesn't working. This is now working with the version tornado==4.5.3

**Comment by mojovski** [comment]
same here. Thanks !
You cant image how important this finding is. It is related many weird issues, people report with bson and apt-get ...

**Comment by florian-leblanc** [comment]
Btw i use the version 4.5.3 but maybe more recent version are working before the 5.0.

**Comment by kinergy** [comment]
> Yea i did something like `pip uninstall tornado` and then `pip install tornado==4.5.3`.

This fixed it for me on Ubuntu 16.04 with ROS Kinetic. Interestingly, Ubuntu 18.04 with ROS Melodic did not require this fix. Not sure why. My specific test case is running the RBSManager example app on iOS to control Turtlesim.

**Comment by mvollrath** [comment]
Thank you for the troubleshooting, I'm adding information on Tornado version issues in #397
