### ISSUE TITLE
Timeout / disconnect problem in 0.9.0

### ISSUE THREAD

**Issue by Schwimo** [RobotWebTools/rosbridge_suite#356]
Hello,

i updated the rosbridge from **0.8.6** to **0.9.0** and had the problem that after **~1min 40s** the **connection** got **disconnected**. 
When downgrading to 0.8.6 again, this problem doesn't occur anymore.

ROS Master:
Kinetic
Ubuntu 16.04

Bridge Client:
Windows 10
WPF App which uses the websocket connection.

**Comment by evenmarbles** [comment]
I am seeing the same issue, though the connection seems to be disconnected fairly immediately after a connection was made on the server side. As mentioned by @Schwimo , downgrading to 0.8.6 fixed the issue (thanks @Schwimo  for figuring this out).

ROS Master:
Kinetic
Ubuntu 16.04

Bridge Client:
Windows 10
Unity with [ROSSharp](https://github.com/siemens/ros-sharp) which requires the websocket connection.

**Comment by mvollrath** [comment]
Is this still an issue in 0.11.0?
