### ISSUE TITLE
Busy wait on advertise service capability

### ISSUE THREAD

**Issue by gonzalocasas** [RobotWebTools/rosbridge_suite#361]
When handling the response of a service, `rosbridge_library` has a busy wait loop checking for dictionary keys' presence. On a quick check, I think we can shave a few ms off of that process by using a `threading.Event` or similar to signal completion.

The busy wait is here:
https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosbridge_library/src/rosbridge_library/capabilities/advertise_service.py#L47

I will prepare and submit a pull request for this change (unless there's a strong reason not to from your side?).

**Comment by mvollrath** [comment]
This would be a good change.  I would probably change the existing `threading.Lock` to a `threading.Condition`.

**Comment by gonzalocasas** [comment]
@mvollrath I didn't send it because there was no response, but if there's interest, I can wrap it up and send a PR in the next couple of days.
