### ISSUE TITLE
Logging service calls; logging in general

### ISSUE THREAD

**Issue by ablakey** [RobotWebTools/rosbridge_suite#362]
I'm using Rosbridge to interface web-based UIs with fleets of >100 robots to monitor and manage their work lifecycle.  I want to know which client calls a specific service and when, but successful service calls are not logged by Rosbridge. It got me thinking about ways to handle this, which led me to the desire to allow clients to log to the ros logs themselves.

We could add the ability for web clients to proxy call  `log*` methods (eg. loginfo). This could be done by extending Rosbridge protocol with a "log" `op`. Though we probably don't want to be extending the Rosbridge protocol like this. Maybe this would be nice for 3.0. 

It could also be done by creating another rosauth API for logging, which is probably a safer, easier solution. I'm probably going to do this anyway by implementing a log* rosservice server. But I thought it might be a great addition to `rosapi`. 

What does everyone think?

**Comment by mvollrath** [comment]
Subscribe to `/rosout` for all ROS logs.  Does this do what you need?
