### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by ablakey** [RobotWebTools/rosbridge_suite#368]
Hello!

It's been about 6 months since 0.9.0 was released. Can we get another tagged release? I'm shipping Rosbridge to a few dozen robot fleets and the current devel branch has some pretty important fixes I'd like to include. 

Thanks!

**Comment by jspricke** [comment]
Hey guys,

we are running into #355, would be great to have it fixed with a new release.

Greetings

Jochen

**Comment by jihoonl** [comment]
Done.
