### ISSUE TITLE
Use of "default" in GetParam.srv creates compiler error.

### ISSUE THREAD

**Issue by jhoare** [RobotWebTools/rosbridge_suite#369]
`default` is a protected keyword in C++, and GetParam.srv has a `default` paramter. If you try to `#include<rosapi/GetParamRequest.h>` it will result in the following compiler error:

```
In file included from /opt/ros/kinetic/include/rosapi/GetParam.h:11:0,
                 from cpp_file:
/opt/ros/kinetic/include/rosapi/GetParamRequest.h:42:17: error: expected unqualified-id before ‘default’
   _default_type default;
```

**Comment by StefanFabian** [comment]
+1

A hack to use this header until this is fixed would be the following:
```
#define default mdefault
#include <rosapi/GetParam.h>
#undef default
```
The default member would be available as mdefault.
