### ISSUE TITLE
--once using rosrun 

### ISSUE THREAD

**Issue by ybchoo** [RobotWebTools/rosbridge_suite#383]
When I execute
rostopic pub /topicname std_msgs/Empty --once
it works and --once is mandatory. Without --once, ros command does not work.

Could gurus at RosBridge help advice on how can I construct my json object?
At present, my Json object before sending to rosbridge
{"topic":"/topicname","type":"std_msgs/Empty","op":"advertise","id":"/topicname"}
{
"topic": "/topicname",
"msg":
{
"data": " --once"
},
"op": "publish",
"id": "/topicname"
}
Thanks n sincerely look forward hearing from you.

**Comment by mvollrath** [comment]
Your problem is the order of arguments, `rostopic pub --once /topicname std_msgs/Empty` will work.
