### ISSUE TITLE
how can i send ros msg to rosbridge_server?

### ISSUE THREAD

**Issue by kimwin2** [RobotWebTools/rosbridge_suite#390]
i found that how to send json msg to rosbridge_server on c++ code.
But it is difficult to find that how to send ros msg to rosbridge_server.

Anybody know the solution?

**Comment by Behery** [comment]
Hi @kimwin2 

what do you mean send a ros msg to rosbridge_server? 
you mean publishing to a topic? in this case maybe [this](http://wiki.ros.org/roslibjs/Tutorials/BasicRosFunctionality#CA-3bc839e9e2d3c2cac3f7fabffacfbda3d5c050ae_32) helps you?

**Comment by mvollrath** [comment]
Rosbridge can relay all ROS messages sent by any node to a websocket client.  You can publish messages with a tool like `rostopic`.  Try asking at [ROS Answers](https://answers.ros.org/)
