### ISSUE TITLE
Question: is it possible to get completion callbacks for the advertise operation?

### ISSUE THREAD

**Issue by gonzalocasas** [RobotWebTools/rosbridge_suite#402]
> Note: I am not sure if this fits better as a question at https://answers.ros.org/, but since it's a pretty concrete question about the protocol, I post it here for now. If you feel it needs to be moved, please let me know.

Is it possible to be notified via callback or any other way, when the `advertise` operation has completed? There is this `status message` ops in the protocol, but they are marked as experimental and also, it does not sound correct to have to set the level to lower (`info`), only to be notified if the operation is completed, and then raise it again to the default `error`.

**Comment by matthijs040** [comment]
I have the same issue. As a simple fix I've made my client retransmit advertise messages periodically to have "kind of a guarantee that it is received" but it is not a clean solution.
