### ISSUE TITLE
Request: New minor release

### ISSUE THREAD

**Issue by gpdas** [RobotWebTools/rosbridge_suite#404]
Would it be possible to have a minor version release (0.11.1) somewhere in the near future?

We are using rosbridge in our project with 30+ researchers. We are using Kinetic. Some of the recent commits in the source are missing in 0.11.0, e.g. [BadYieldError](https://github.com/RobotWebTools/rosbridge_suite/blob/2b2326825a18eb4dceec346c7a7bdad5db447b49/rosbridge_server/src/rosbridge_server/websocket_handler.py#L176-L181) and [warning string formatting error](https://github.com/RobotWebTools/rosbridge_suite/pull/398). It would be easier for our large team to have binaries.

Thanks in advance.

**Comment by jihoonl** [comment]
https://github.com/ros/rosdistro/pull/21112
https://github.com/ros/rosdistro/pull/21113
