### ISSUE TITLE
Feature Request: Provide method for retrieving message definitions

### ISSUE THREAD

**Issue by gkjohnson** [RobotWebTools/rosbridge_suite#416]
Just like rosbridge provides a method for requesting [ros topic types](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosapi/src/rosapi/proxy.py#L137) it would be great to provide a method for retrieving ros message definitions using something like the [get_msg_text](https://github.com/strawlab/ros_comm/blob/master/tools/rosmsg/src/rosmsg.py#L229) function the `rosmsg` utility.

Specifically I'm interested in using this with Roslibjs to dynamically infer message types and help to automate some message processing on the client.

Thanks!

**Comment by uahic** [comment]
For typechecking however (tyepscript) I dont see how this would help during development time. What I do is to just write interfaces that mirror the message types (that helps alot for coding, especially autocompletion) but yeah... alot of manual typing. Hence -> typescript ;)

**Comment by gkjohnson** [comment]
#452 closed this issue

**Comment by jtbandes** [comment]
For ROS 2, see also #574 and https://github.com/ros2/ros2/issues/1159
