### ISSUE TITLE
Auth not working properly since Autobahn websocket server

### ISSUE THREAD

**Issue by reinzor** [RobotWebTools/rosbridge_suite#434]
## Expected Behavior

Authentication should work with multiple clients.

## Actual Behavior

When multiple clients set-up an auth connection, at some point the auth service is not called and the client is not authenticated. When running the authenticated websocket server separately, it seems that it hangs and does not respond on any incoming connections.

## Steps to Reproduce the Problem

  1. Start websocket server with authentication
  1. Open auth connection with client 1
  1. Open auth connection with client 2
  1. Refresh pages of clients a couple of times

I could only reproduce this when the system is under some load. With a simple set-up, this does not occur. 

## Specifications

  - ROS Version (`MELODIC`):
  - OS Version (`Ubuntu 18.04 LTS`):
  - Rosbridge Version (`3b375b23a4bc36cdc0d79fab8914def77951ded4`):
  - Twisted Version (`[Twisted, version 17.9.0]`):

**Comment by mvollrath** [comment]
@reinzor I can't find documentation about how to run the authenticate service, can you point me at some information so I can try to repro this?

**Comment by reinzor** [comment]
This is indeed not properly documented (maybe we should add some documentation in the rosbridge aswell).

Rosauth package doc: http://wiki.ros.org/rosauth

then call the `authenticate` method on the `roslibjs` ROS connection instance

**Comment by reinzor** [comment]
However, after more testing, it seems to hang only under heavy load so maybe this might be related to https://github.com/RobotWebTools/rosbridge_suite/issues/425

**Comment by mvollrath** [comment]
@reinzor is this still an issue?

**Comment by reinzor** [comment]
Yes, for now I reduced the bandwidth and it seems to work fine but for high loads, authentication seems to fail for some reason. It seems that something is "hanging".

**Comment by mvollrath** [comment]
I tried to repro this but couldn't get it to auth properly under normal conditions.  I'm happy to debug this when there's documentation on how to set it up.

**Comment by mvollrath** [comment]
You might find this works better with https://github.com/RobotWebTools/rosbridge_suite/pull/464

**Comment by reinzor** [comment]
We will try this out! Thanks

**Comment by reinzor** [comment]
Seemed to be coupled to https://github.com/RobotWebTools/rosbridge_suite/issues/425 , no longer deserves a separate issue.
