### ISSUE TITLE
Autobahn support breaks Python 3.

### ISSUE THREAD

**Issue by mikepurvis** [RobotWebTools/rosbridge_suite#448]
As of #426, we get the following error under Python 3:

```
File ".../lib/python3/dist-packages/rosbridge_server/autobahn_websocket.py", line 180, in onMessage
  self.protocol.incoming(message)
File ".../lib/python3/dist-packages/rosbridge_library/protocol.py", line 120, in incoming
  self.buffer = self.buffer + message_string
builtins.TypeError: Can't convert 'bytes' object to str implicitly  
```

Would be great to have a CI setup that ran tests under Py3 as well as Py2.

**Comment by mvollrath** [comment]
I'll work on fixing this.

> Would be great to have a CI setup that ran tests under Py3 as well as Py2.

Rosbridge uses the [industrial_ci](https://github.com/ros-industrial/industrial_ci/blob/master/README.rst) script for which [Python 3 support is in progress](https://github.com/ros-industrial/industrial_ci/pull/429).
