### ISSUE TITLE
Websocket connection from localfile origin fails

### ISSUE THREAD

**Issue by Axel13fr** [RobotWebTools/rosbridge_suite#454]
## Expected Behavior
The websocket shall allow a connection from a local file origin (ex: file://mypage.html), provided the user set a parameter.

## Actual Behavior
The autobahn websocket refuses connections from local origins. It requires an extra option to allow it. The parameter is not accessible from ros params.

## Steps to Reproduce the Problem

  1.Load a local  page which connects the websocket.

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): Ubuntu 18.04
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 1.0.2
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 19.10.0

###Solution:

Autobahn convert local file origins to a null origin. One can allow local origins to work by allowing Null origin:
```diff
@@ -276,6 +276,7 @@ if __name__ == "__main__":
         perMessageCompressionAccept=handle_compression_offers,
         autoPingInterval=ping_interval,
         autoPingTimeout=ping_timeout,
+        allowNullOrigin=True
     )
```

**Comment by boilerbots** [comment]
Yes please. We run a browser locally to display a status and use the local file option so we don't need to maintain an html server on a robot.

**Comment by boilerbots** [comment]
Also, should big changes be made to Melodic, it was released 2 years ago and people might expect it to be stable.

**Comment by Axel13fr** [comment]
Check https://github.com/RobotWebTools/rosbridge_suite/pull/463
But it doesn't pass tests on kinetic probably because the autobahn version of kinetic doesn't have this null origin parameter.

**Comment by boilerbots** [comment]
> Check #463
> But it doesn't pass tests on kinetic probably because the autobahn version of kinetic doesn't have this null origin parameter.

Well, there could be a branch for Kinetic, Melodic and so on. They all don't have to run the exact same code.

**Comment by boilerbots** [comment]
This works in Melodic and 18.04: https://github.com/RobotWebTools/rosbridge_suite/pull/469
