### ISSUE TITLE
FieldTypeMismatchException occurred when calling 'std_srvs/srv/SetBool' type service

### ISSUE THREAD

**Issue by TeamATR** [RobotWebTools/rosbridge_suite#461]
### Expected Behavior

call type `std_srvs/srv/SetBool` service, set data to True or False.

### Actual Behavior

FieldTypeMismatchException error occurred.

### Steps to Reproduce the Problem

e.g.
```python 
service = roslibpy.Service(client, '/set_ludicrous_speed', 'std_srvs/srv/SetBool')
request = roslibpy.ServiceRequest({"data": True})
result = service.call(request)
```

### Specifications

  - ROS Version : `ROS2 - dashing`
  - OS Version : `linux 18.04`
  - Rosbridge Version : `dashing`

### Reason

The class `std_srvs.srv._set_bool.py` used in my environment defines `boolean` instead of using `bool` as follows:
```python
    _fields_and_field_types = {
        'data': 'boolean',
    }

    SLOT_TYPES = (
        rosidl_parser.definition.BasicType('boolean'),  # noqa: E501
    )
```
I added `boolean` into `type_map` and `ros_primitive_types` in `message_conversion.py` for quick solution. The prior pull request is [https://github.com/RobotWebTools/rosbridge_suite/pull/455](https://github.com/RobotWebTools/rosbridge_suite/pull/455). But I am not sure which side the problem is in, `std_srvs` library or `rosbridge`.

**Comment by dirk-thomas** [comment]
The type `boolean` shown above is the IDL type of the field (see http://design.ros2.org/articles/mapping_dds_types.html). In Python that is mapped to a `bool` (see http://design.ros2.org/articles/idl_interface_definition.html#type-mapping).
