### ISSUE TITLE
WebSocketClosedError: Tried to write to a closed websocket

### ISSUE THREAD

**Issue by ding511265378** [RobotWebTools/rosbridge_suite#462]
Now I have a rosbag packets and play it, front end by subscribing to different themes and invoke the callback function to real-time access to data, the code is written according to the official tutorial.
My question is: when I only subscribe to a few topics (e.g. 1 ~ 3) and the callback function is invoked, the front-end data acquisition,  seems everything is normal, but at the same time to subscribe to multiple topics (e.g. 7 ~ 8 or more), the front-end not accept data and appear the following error, WebSocketClosedError: Tried to write to a closed websocket.
Could you tell me where is the problem?How?

ROS Version (echo $ROS_DISTRO): kinetic
OS Version (grep DISTRIB_CODENAME /etc/lsb-release): xenial
Rosbridge Version (roscat rosbridge_server package.xml | grep '<version>'): 0.11.3
Tornado Version (python -c 'import tornado; print tornado.version'): 4.2.1

**Comment by stardobas** [comment]
me too...

**Comment by ding511265378** [comment]
> me too...

You can try out rosnodejs, which seems to work just fine
