### ISSUE TITLE
rosbridge server error on basic usage

### ISSUE THREAD

**Issue by NikolaasBender** [RobotWebTools/rosbridge_suite#485]
```
2020-04-20 16:24:20-0600 [-] failing WebSocket opening handshake ('WebSocket connection denied: origin 'file://' not allowed')
2020-04-20 16:24:20-0600 [-] dropping connection to peer tcp4:127.0.0.1:38328 with abort=False: WebSocket connection denied: origin 'file://' not allowed
```
js error message
```
WebSocket connection to 'ws://localhost:9090/' failed: Error during WebSocket handshake: Unexpected response code: 400
Ros.connect @ roslib.js:2224
Ros @ roslib.js:2202
(anonymous) @ tab_manager.js:4
```
This error occurs with basic usage when trying to connect roslibjs to a roscore on version 0.11.4.

## Steps to Reproduce the Problem

  1. update to rosbridge server to 0.11.4
  2. run ```ros.on('error', function(error) { console.log( "connection error:" ); console.log( error ); }); ros.on('connection', function() { console.log('Connection made!'); });```
  3. observe the error in rosout and in the electron inspector

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): Melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): Bionic
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.4
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): [Twisted, version 17.9.0]

**Comment by mvollrath** [comment]
Fixed by #469 in 0.11.5
