### ISSUE TITLE
External Port should be disabled when not set. 

### ISSUE THREAD

**Issue by pramodhkp** [RobotWebTools/rosbridge_suite#489]
## Expected Behavior
If `websocket_external_port` is not set, then rosbridge should pass `None` to the autobahn library. This should disable the external port check. (https://github.com/crossbario/autobahn-python/issues/1360#issuecomment-614411125)

## Actual Behavior
The default value of `websocket_external_port` is set to the `port` value. This doesn't disable `externalPort` check even if it's not set. 

Let me know if you have any suggestions about this. I am working on a fix for this. I can submit a PR to fix this.

**Comment by mvollrath** [comment]
This seems worthwhile, PR would be welcome.  For better or worse, the legacy of rosbridge is insecure by default, but at least now there will be params to lock it down.
