### ISSUE TITLE
Roadmap for newer ROS2 versions

### ISSUE THREAD

**Issue by felixdivo** [RobotWebTools/rosbridge_suite#498]
Currently, [ROS Index](https://index.ros.org/search/?term=rosbridge_suite) lists this package as only supporting `dashing` on RSO2. What are the plans for supporting newer versions? Can such plans already be found somewhere? Our search was sadly not successful.

We in our case were surprised to find that apt does not know `ros-eloquent-rosbridge-suite`.

**Comment by felixdivo** [comment]
Guess we'll switch to https://github.com/RobotWebTools/rclnodejs.

**Comment by amacneil** [comment]
ROS 2 version of rosbridge will be published soon. Please follow https://github.com/RobotWebTools/rosbridge_suite/issues/536 for updates (that issue is newer but has more activity).
