### ISSUE TITLE
Message throughput

### ISSUE THREAD

**Issue by MoffKalast** [RobotWebTools/rosbridge_suite#499]
This is not an issue per se, just a general question and discussion. 

I've been wondering how many websockets does rosbridge actually run while connected? What would make sense would be one socket per topic, but from what I've skimmed the code it would appear to only have one websocket for the entire operation?

Asking because I've been running into some major head-of-line blocking with high frequency of messages under less than ideal wifi conditions. Now there are various ways to solve that, but if all topics are being sent from the same tcp queue the improvement won't be great.

Would it make sense to just open multiple top level connections instead (which would appear as multiple clients) and using time critical topics on separate ones?

Thanks.

**Comment by mvollrath** [comment]
Try it and see, I would optimize compression selection, throttle rates, queue lengths, and decouple client-side handlers from the WebSocket message handler before doing anything like that, but theoretically having multiple sockets could factor out some of that decision-making at a (maybe) small overhead cost.

If multiple sockets is the general answer to performance problems it means to me that either rosbridge is failing at performance or it's too much work to tune rosbridge for performance.
