### ISSUE TITLE
split ros msg <> json conversion into separate package

### ISSUE THREAD

**Issue by jonbinney** [RobotWebTools/rosbridge_suite#5]
The functions in rosbridge_suite.internal.message_conversion are generally useful, and it would be nice if they were in their own package

**Comment by jihoonl** [comment]
I don't think rosbridge will integrate rospy_message_converter. reopen it if it will.

**Comment by Interpause** [comment]
I discovered functionality for conversion to and between Python dictionaries (& consequently JSON) seem to be present in [rosidl_runtime_py](https://github.com/ros2/rosidl_runtime_py):

https://github.com/ros2/rosidl_runtime_py/blob/1979f566c3b446ddbc5c3fb6896e1f03ccbc6a27/rosidl_runtime_py/set_message.py#L28-L37

https://github.com/ros2/rosidl_runtime_py/blob/1979f566c3b446ddbc5c3fb6896e1f03ccbc6a27/rosidl_runtime_py/convert.py#L159-L176

I am not sure if there is an equivalent in ROS1, but if there is, maybe this could be used instead (perhaps more reliable?).
