### ISSUE TITLE
ssh remap && rosweb

### ISSUE THREAD

**Issue by panecho** [RobotWebTools/rosbridge_suite#505]
I have two computers  **A**(ip: 192.168.3.99) and **B** in local network, and **B** can access **A** with SSH;
**A** runs ros node and rosbridge_suite websocket.launch on default port 9090;
On **B**, I use ssh to remap **A:9090** to **B:5421** (ssh -f -N -L 5421:192.168.3.99:9090 192.168.3.99); 

## Expected Behavior
Supervise rosmsg from **A** on **B** with rosweb;

Using [ rosbweb ](http://labrom.eesc.usp.br/rosweb/) to supervise rostopic on **A** with connection showed as picture below:
![image](https://user-images.githubusercontent.com/15884732/83219073-fa567c80-a1a1-11ea-87a5-8659c6ab26f7.png)

## Actual Behavior
unable to connect , of course can't receive any ros msg from **A**;

## Steps to Reproduce the Problem

  1. run rosnode and websocket.launch on **A**;
  2. remap **A:9090** to **B:5421** on **B**;
  1. using rosweb on **B** to supervise rostopic from **A**;

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): kinetic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`):DISTRIB_CODENAME=xenial
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`):<version>0.11.6</version>
  - Twisted Version (`python -c 'import twisted; print twisted.version'`):[twisted, version 16.0.0]

**Comment by mvollrath** [comment]
This should work by default starting in 0.11.7.
