### ISSUE TITLE
Defragmentation TODOs

### ISSUE THREAD

**Issue by baalexander** [RobotWebTools/rosbridge_suite#51]
There were a few TODO items in the defragmentation code inside Pull Request #48. I'm moving the items to this ticket for safe keeping and to track the progress.
- [ ] Add integration with rosauth in rosbridge_tcp
- [ ] Adjust max_msg_length value based on further testing in rosbridge_tcp
- [ ] Add documentation
- [ ] Add exception handling
- [ ] Add type checking
- [ ] In defragmentation.py, use String.join() instead of "+=" to improve performance during message reconstruction

**Comment by Kiloreux** [comment]
- [x] In defragmentation.py, use String.join() instead of "+=" to improve performance during message reconstruction
#207
