### ISSUE TITLE
Exception in deserialization of BSON with ROS Noetic

### ISSUE THREAD

**Issue by repa1030** [RobotWebTools/rosbridge_suite#515]
##  Expected Behavior
ROSBRIDGE Server works fine with ROSSharp and BSON serialization such as in ROS Melodic.

## Actual Behavior
Getting Error:
[Client 0] Exception in deserialization of BSON

## Steps to Reproduce the Problem
  1. Use current ROSBRIDGE develop branch
  2. Use current ROSSharp branch
  3. Send any message with BSON serialization

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): Noetic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): Focal
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.9
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 18.9.0

**Comment by RyodoTanaka** [comment]
I have the same error, does any one have the solution ... ?

**Comment by nick-paul** [comment]
#545 Fixes some major python3/BSON issues. Does using that branch resolve the issue?

**Comment by repa1030** [comment]
Yes, fixed :)
