### ISSUE TITLE
When running with python3, data transmission is very lagging

### ISSUE THREAD

**Issue by wgenesis** [RobotWebTools/rosbridge_suite#535]
## Expected Behavior
I use python3 to run rosbridge_websocket.py to communicate with lgsvl.

## Actual Behavior
The data transmission between the pointcloud and the camera has a lag, but there is no such problem with Python2.

So what 's the problem?

Thanks.

**Comment by amacneil** [comment]
This issue is stale and has not received a response so I will close it.

If this is still an issue, please provide complete steps to reproduce.

**Comment by RalphCodesTheInternet** [comment]
Any solution on this yet? My topics also have significant lag.
