### ISSUE TITLE
Invalid cert for wss on LAN

### ISSUE THREAD

**Issue by pringithub** [RobotWebTools/rosbridge_suite#538]
I am trying to network multiple devices on a network over https and wss.

One machine (running ROS) acts as a server, serving a web page, securing it via ngrok. It also hosts a wss listener. The second machine (not running ROS) connects to the secure endpoint, and attempts to connect to the first machine over wss. The error I get when this occurs is a net::ERR_CERT_AUTHORITY_INVALID error.

The strange thing is that when I run both server and client on the same machine, and specify wss://localhost:port as the endpoint, everything works fine. However, when I change the endpoint to wss://192.168.1.253:port on the same computer, I see the error again.

With just http and ws://192.168.1.253:port, the application works fine.

I've spent quite a lot of time digging through other's questions related to this, searched proxying methods, but haven't found a solution. I even wrote my own backend server in nodejs to accept connections using the `rejectUnauthorized: false` parameter. This gives me a warning, but I am still able to connect: `(node:9451) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.`

I've also seen other people have similar issues with wss, but it seems, but I haven't seen anyone with this particular problem

How I generated my keys: `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes`

Command to launch the server (ROS-based): `roslaunch rosbridge_server rosbridge_websocket.launch ssl:=true keyfile:=$PWD/key.pem certfile:=$PWD/cert.pem`

[Basic Architecture](https://i.stack.imgur.com/pSC0l.png)

## Specifications

  - ROS Version (melodic):
  - OS Version (18.04=bionic):
  - Rosbridge Version (0.11.10):
  - Twisted Version (17.9.0):

**Comment by Interpause** [comment]
Bump, having same issue as well. Might be related to https://stackoverflow.com/questions/59880989/ssl-certificate-unknown-error-when-connecting-to-http-tornado-server.
