### ISSUE TITLE
rosbridge cannot connect using DDNS

### ISSUE THREAD

**Issue by Benjaminmar8** [RobotWebTools/rosbridge_suite#543]
I have configured rosbridge server and the web page is served by an Apache server running on the same ROS PC. The ROS PC is connected to a 4G-enabled WiFi router. I am able to access the web page and connect to the robot via rosbridge if the client PC is in the same intranet as the ROS PC, namely the client PC is connected to the router. Now, we inserted a SIM card in the router and configured the router's DDNS setting. When we use the remote PC to access the web page using 4G network, the page is loaded but the rosbridge cannot connect. What could be the issue?

Specifications

  - ROS Version (`echo $ROS_DISTRO`): Melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): Ubuntu 18.04

**Comment by amacneil** [comment]
Closing stale issue since it is not rosbridge specific.

There are many reasons the above may not work, but most likely the websocket port is not being correctly exposed on a public IP.

That said, exposing rosbridge on a public IP is not recommended since it has no built in authentication.
