### ISSUE TITLE
Rosbridge import error: No Module name builtins

### ISSUE THREAD

**Issue by MishkaMN** [RobotWebTools/rosbridge_suite#544]
Previous version of 0.11.10-1 was working fine until it was updated to 0.11.12-1. Module seem to not be found.

## Expected Behavior

`roslaunch rosbridge_server rosbridge_websocket.launch port:=9090` should not fail.

## Actual Behavior

It says the following error:

![image](https://user-images.githubusercontent.com/20613282/101680219-60b03780-3a2e-11eb-8678-bf2e3e77027d.png)
![image](https://user-images.githubusercontent.com/20613282/101680282-74f43480-3a2e-11eb-83da-1d9010a0e805.png)

## Steps to Reproduce the Problem

the server is on here https://github.com/usdot-fhwa-stol/carma-platform
we call it from launch file here https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/carma/launch/ui.launch

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): kinetic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): xenial
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.12
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): [twisted, version 16.0.0]

**Comment by msmcconnell** [comment]
The fix for this is to install the futures package for python2
```
pip install future
```
I'm not sure if this is something missing from the rosbridge apt binaries or if its expected to be downloaded separately.

**Comment by mvollrath** [comment]
This is fixed in 0.11.13

**Comment by alexytsu** [comment]
I assume there is going to be a couple weeks wait before this fix will land and be released through the ros debian mirrors? 

Is the only way to patch this in the meantime to uninstall the `apt` version and build from source?

**Comment by mvollrath** [comment]
You can install the `future` Python package for Python 2 as a workaround, for most users I would highly recommend installing it via your distro's package manager instead of pip.  e.g. `apt install python-future` on Debian/Ubuntu.
