### ISSUE TITLE
QoS compatibility failing silently (ROS2)

### ISSUE THREAD

**Issue by DomenicP** [RobotWebTools/rosbridge_suite#551]
**Edit**: I originally thought the problem I encountered was related to custom message definitions, but it turns out that the problem was actually regarding ROS2 QoS settings. As such I have updated the issue description.

## Expected Behavior

`rosbridge_server` should allow clients to subscribe to a topic regardless of the QoS settings for that topic.

## Actual Behavior

`rosbridge_server` silently fails to subscribe to topics with publishers that use **Best Effort** reliability instead of **Reliable.** The `rosbridge_server` logs indicate that the client connected and that the subscription was created, but no data is ever received in the subscriber callback.

```
[INFO] [1611352924.485146047] [rosbridge_websocket]: Client connected. 1 clients total.
[INFO] [1611352926.636802670] [rosbridge_websocket]: [Client 1] Subscribed to /my_topic
```

According to the [QoS documentation](https://index.ros.org/doc/ros2/Concepts/About-Quality-of-Service-Settings/#qos-compatibilities), "a connection between a publisher and a subscription is only made if the pair has compatible QoS profiles." For the reliability QoS policy, all combinations are compatible except for when the publisher uses **Best Effort** and the subscriber uses **Reliable**. Based on my recent experience, it would seem that a failure to connect based on QoS compatibility either fails silently or requires more verbose logging than I currently have configured. 

The rosbridge subscriptions are initially created here:

https://github.com/RobotWebTools/rosbridge_suite/blob/1a2c386455067b00a9e67fb70cc711add38c3582/rosbridge_library/src/rosbridge_library/internal/subscribers.py#L108

It looks like `rosbridge_server` uses the default reliability QoS policy (which in my case ends up being **Reliable**) and only specifies the depth. Would it be better to have the rosbridge subscribers use a **Best Effort** QoS policy? I'm not super familiar with how things work behind the scenes, but from what I read in the documentation it sounds like a subscriber that requests **Best Effort** from a publisher that provides **Reliable** will still end up with **Reliable** QoS. The rosbridge protocol makes no mention of QoS since it's a new concept in ROS2, so the client doesn't currently have a way to request a specific QoS profile.

## Steps to Reproduce the Problem

  1. Run a ROS2 node that publishes data to a topic using **Best Effort** reliability.
  2. Run `rosbridge_server` and attempt to subscribe to that topic using a rosbridge client library (roslibpy, roslibjs). The subscriber should not receive any data.
  3. Change the reliability policy on the publisher to **Reliable** and repeat step 2. The subscriber should now receive data from the publisher.

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): foxy
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): focal
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 1.0.2 (more specifically 1a2c386)
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): `tornado.version == 5.1.1`

**Comment by jtbandes** [comment]
Should be fixed by #690
