### ISSUE TITLE
[ROS2] Visualization markers error

### ISSUE THREAD

**Issue by AndrewJSchoen** [RobotWebTools/rosbridge_suite#560]
## Expected Behavior
After publishing a marker message to `/visualization_marker`, the message will be funneled through the rosbridge web socket server to the web.

## Actual Behavior
An exception is raised when calling the subscribe callback:
`Exception calling subscribe callback: a bytes-like object is required, not 'str'`
The callback is a `<bound method Subscription.on_msg of <rosbridge_library.capabilities.subscribe.Subscription object at 0x178faeb50>>`
And the message is of type `OutgoingMessage`

Of note, the markers are valid messages, and appear as expected in RVIZ2

## Steps to Reproduce the Problem

  1. Start ros2 rosbridge web socket node
  1. Publish visualization marker message to `/visualization_marker`
  1. Observe error

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): FOXY
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): MacOS 11
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 1.0.2 (ROS2)
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 20.3.0

## Last note
It does seem like this works fine with the `ros2-web-bridge`

**Comment by jtbandes** [comment]
Hi, we've made some changes for ROS 2 compatibility and tested with Galactic. The package will be released soon with the next Foxy & Galactic syncs. Can you please try again with the latest `ros2` branch and see if you're still having problems?

> OS Version (grep DISTRIB_CODENAME /etc/lsb-release): MacOS 11

Are you trying to run ROS on macOS, or just connecting to the WebSocket bridge from macOS? Which Linux release are you using to run ROS?
