### ISSUE TITLE
Can't execute launch file "rosbridge_tcp.launch"

### ISSUE THREAD

**Issue by arizk2605** [RobotWebTools/rosbridge_suite#566]
Hi everyone,
I try to listen to a streaming server ( host : "127.0.0.1", port = "28000") using the "rosbridge_tcp.launch" file but the process dies because of this : 
![image](https://user-images.githubusercontent.com/16838446/115255647-c45e1600-a12e-11eb-8d58-c834165216ba.png)

Knowing that i had the same kinda problem with TypeDef msgs in rosapi and i solved it by changing the name of the rosapi folder contained in the rosapi package folder to "rosapi_intern". I also tried to change  the "rosapi_intern" dependecies in package.xml of the same package but it didn't seem to make any effect.

My main objective would be to publish some data provided by a streaming server delivering some data from a wristband to tcp clients.

**Comment by Ragingram2** [comment]
is this for Ros1? or Ros2?

**Comment by arizk2605** [comment]
ros 1 melodic
