### ISSUE TITLE
Weird delay between ROS and browser

### ISSUE THREAD

**Issue by cheng0425** [RobotWebTools/rosbridge_suite#573]
Hi, 

We are using rosbridge to communicate with a Chrome browser which is built by roslibjs. There is a delay in the message transmission between ROS and browser. Our goal is to keep delay within 350ms.   
For future use, we are searching for the maximum number of topics that rosbridge can afford to transmit. So we let the browser subscribe to n topics published by ROS.  

But the result seems to be different from what we expected.  
We have confirmed that the main delay occurs between rosbridge and browser, not between ROS and rosbridge.  
Does anyone else have the same problem or know why this is happening?  

## Expected Behavior
According to the results while the number of topics is less than 15, the delay grows as the message size increases. So we expect the same result while the number of topics is 15.    
> PS. The delay refers to the elapsed time between being published (header.stamp) and reaching the subscriber's callback function on the browser.

## Actual Behavior
Here is our result. Each spot represents the average of the results of about three experiments. The average delay in the y-axis means the average delay of a topic. And the publish rate of each topics is 60Hz.  

There is an obvious rise in the range (0.5, 1.0) and then returns to normal again when message size>1KB.  
This weird case also occurs while n>15.  
![image](https://user-images.githubusercontent.com/81609437/124845144-0df12b00-dfd1-11eb-825e-59cb5ba6e31f.png)

## Steps to Reproduce the Problem

  1. Start our ROS system to control the robot. 
  1. Launch the rosbridge_websocket.launch with default values of parameters.   
We modified the parameters in [subscribers.py#line98](https://github.com/RobotWebTools/rosbridge_suite/blob/develop/rosbridge_library/src/rosbridge_library/internal/subscribers.py#L98) for some needs.   
```
self.subscriber = Subscriber(topic, msg_class, self.callback, queue_size=1, TCP_NODELAY=true)
```  
  3. Build up n nodes that publish n topics.  
  4. Open the browser which subscribes to these n topics and also /tf2_web_republisher/feedback to get the robot's status in real time.
  5. Start calculating the average delay for each topic. 

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): melodic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): bionic
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): 0.11.13
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 17.9.0

**Comment by RalphCodesTheInternet** [comment]
Did you solve the problem yet? I am facing a similar problem. I read somewhere that python3 could be the culprit, but still testing
