### ISSUE TITLE
About not being able to subscribe to custom topics

### ISSUE THREAD

**Issue by CTGUMARK** [RobotWebTools/rosbridge_suite#607]
Why can’t I transmit a custom message format? For example, I defined a slef.msg that contains two arrays. The topic can be printed out on the ros machine, but it can’t be monitored on the web page. Thank you

**Comment by meyerjo** [comment]
Did you find a solution?

**Comment by CTGUMARK** [comment]
> Did you find a solution?

A solution has been found, the current reason should be that I did not add the topic type when listening on the web side
