### ISSUE TITLE
how can I install this packages (ros2 foxy) as a python module, so that I can import the bridge_library in my python code

### ISSUE THREAD

**Issue by makeadl** [RobotWebTools/rosbridge_suite#626]
## Actual Behavior
I can clone this repo in my workspace, but i have that problem, that i cannot import it as a module in my python Code
![image](https://user-images.githubusercontent.com/56048113/130252838-4854b92c-94ec-41b3-b7b2-5ab12efb5e66.png)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - ROS Version (`echo $ROS_DISTRO`):
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`):
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`):
  - Tornado Version (`python -c 'import tornado; print tornado.version'`):

**Comment by jtbandes** [comment]
Have you tried `colcon build` followed by `source install/setup.bash`?

**Comment by makeadl** [comment]
yes I build all these ros packages and I source also my workspace but to install these ros packages as a python modules  I guess, I need a file like setup.py to install it.

**Comment by amacneil** [comment]
There will be an apt release of rosbridge in the next sync (Galactic sync is [tomorrow](https://discourse.ros.org/t/new-packages-for-galactic-geochelone-2021-07-16/21418), I'm not sure when Foxy sync is). This should be easier than installing from source.

If you're still having issues, please post on [ROS Answers](https://answers.ros.org/questions/).
