### ISSUE TITLE
Unable to locate package (noetic)

### ISSUE THREAD

**Issue by woelde77** [RobotWebTools/rosbridge_suite#637]
## Expected Behavior
Hey all, I want to install rosbridge with:

> sudo apt install ros-noetic-rosbridge-suite

but it can't locate the package

## Actual Behavior
![Screenshot from 2021-09-06 21-59-12](https://user-images.githubusercontent.com/90217712/132257684-97140597-1c45-4dc9-887d-3968d0f446bc.png)

## Specifications

  - ROS Version: noetic 
  - OS Version: ubuntu 20.04

**Comment by amacneil** [comment]
See https://github.com/RobotWebTools/rosbridge_suite/issues/619#issuecomment-902437941
