### ISSUE TITLE
Websocket has high latency - How to find origin of lag?

### ISSUE THREAD

**Issue by jstiefel** [RobotWebTools/rosbridge_suite#642]
**Description**

I have a webinterface subscribing to an image stream (over the websocket) and a nippleJS joystick to control my robot. However, sometimes there is a lag building up. On my server, I see that CPU load is relatively high due to the image processing node. But on the local server, the image stream looks fine (using image_view). When I move the nippleJS around very fast, CPU load seems to increase for the browser process. The image stream is 1920p, 20ps and an image_raw/compressed topic. The joystick publisher has a Timer so that the max. publishing frequency is 20 Hz. 

Is there any way to debug the websocket. It's really hard to understand why the CPU load of the browser goes up. I'm trying to understand if I'm limited by the network latency and the amount of data or the javascript running in the client's browser. Any way of getting numbers about latency of the image stream or if the joystick commands are actually published with the right frequency? Any way of getting timestamps to compare? Not really sure how I'm going to debug this.

- Library Version: 0.11.13
- ROS Version: Noetic
- Platform / OS: Ubuntu 20.04

**Steps To Reproduce**

Hard to reproduce. It seems to be connected to my application which has an image stream and a joystick. Unfortunately, I can't share the code.

**Expected Behavior**

No visible delay building up over time.

**Actual Behavior**

The image stream and joystick start to have a delay. It is not clear to me if this is due to the connection or the CPU load for the client's browser going up.

**Comment by jstiefel** [comment]
There was a misinterpretation. The CPU load actually comes from the browser.

**Comment by amacneil** [comment]
> There was a misinterpretation. The CPU load actually comes from the browser.

To clarify, does that mean the issue can be closed?

**Comment by jstiefel** [comment]
> > There was a misinterpretation. The CPU load actually comes from the browser.
> 
> To clarify, does that mean the issue can be closed?

I've just updated my initial post. Issue is still open and I'm happy for hints.

**Comment by jtbandes** [comment]
I would recommend first trying the profiling tools built into Chrome (or other browsers). That will hopefully help you understand what the bottleneck is. https://blog.appsignal.com/2020/02/20/effective-profiling-in-google-chrome.html

**Comment by mvollrath** [comment]
In noetic, subscribe topics with queue_length of 1 to prevent backlogging.  This will potentially drop messages, so only do it where that is appropriate (e.g. image streams are perfectly appropriate, you don't actually need to draw every frame).

**Comment by jstiefel** [comment]
> In noetic, subscribe topics with queue_length of 1 to prevent backlogging. This will potentially drop messages, so only do it where that is appropriate (e.g. image streams are perfectly appropriate, you don't actually need to draw every frame).

It's totally appropriate for my real time control. But I think the subscriber queue_length is already 1 per default. The hint says 0 means "no queueing". I hope this is right, because in ROS 0 means "infinite queueing". Anyway, I set it to 1 now.

https://github.com/RobotWebTools/roslibjs/blob/27b747662a4a72d1191442aaebc47f77d161c5a9/src/core/Topic.js#L25

I don't really understand the hint of the `queue_size` parameter, but is this the publisher queue size? I will set it to 1 as well:
https://github.com/RobotWebTools/roslibjs/blob/27b747662a4a72d1191442aaebc47f77d161c5a9/src/core/Topic.js#L23

How is roslib.js handling the subscriber, publisher and callback queue? I've read that it is event driven and asynchronous. But what is happening asynchronous?

**Comment by jstiefel** [comment]
I actually think there is a performance issue with my javascript, mainly the joystick. So this might not be ROS related, if I interpret the performance metrics from Chrome correctly. The red FPS appear during nippleJS joystick movements.
![performance_nanoflex](https://user-images.githubusercontent.com/44534970/135125550-a704ffd4-dfd4-4bf0-b821-63ba092dd5ca.png)

**Comment by jstiefel** [comment]
I think I fixed the performance issues. It seems like rosbridge was not the limiting factor. Sorry for the post at the wrong place, but it helped me anyway to debug. With the help of the Performance tool, I figured out that the handler of the nippleJS joystick, which calls a `innerHTML` function a lot is causing the high CPU load.
