### ISSUE TITLE
ros bridge can not parse json string correctly

### ISSUE THREAD

**Issue by ZBoIsHere** [RobotWebTools/rosbridge_suite#662]
**Description**
help me!
```
srv Description
string map_type  # type of map, enumeration {"Occupancy", "Elevation"}
string map_source_url  # path of map in huawei OBS
---
bool success  # status of this service, true or false
string error_code "None"  # return error_code if success status is false, otherwise return "None"
string error_msg "None"  # return error_msg if success status is false, otherwise return "None"
```
call_service
{"op":"call_service","service":"/update_map","args":{"map_type":"Occupancy","map_source_url":"https://rosrobot.obs.cn-east-3.myhuaweicloud.com/map_data/map-uploader.zip"}}

service_response
{"op": "service_response", "service": "/update_map", "values": "handle_request() takes 2 positional arguments but 3 were given", "result": false}

- Library Version:
- foxy
- ROS Version:
- 2
- Platform / OS:
- ubuntu

what's the correct json format of call_service?

**Comment by jtbandes** [comment]
I believe this will be fixed by https://github.com/RobotWebTools/rosbridge_suite/pull/652.
