### ISSUE TITLE
the "id" field in messages is not used for subscriptions

### ISSUE THREAD

**Issue by dogoepp** [RobotWebTools/rosbridge_suite#673]
When subscribing to topics from a websocket client, I would like that the data in the ID field in my subscription operation be used in subsequent messages from the ros topic.

For instance, if I send

```json
{
  "op": "subscribe",
  "topic": "/text",
  "id": "subscription-to-topic-text-for-the-sake-of-good"
}
```

I would like that messages contain the same ID field.

```json
{
  "op": "publish",
  "topic": "/text"
  "id": "subscription-to-topic-text-for-the-sake-of-good"
  "msg": {
      "data": "Here we go"
  },
}
```

Since it seemed rather simple to implement, I am preparing a Pull Request for that.

**Comment by 6-000-000** [comment]
Any updates on this? Looking for this feature as well. Will this work on ROS2 if ever?
