### ISSUE TITLE
rolling InvalidServiceException error

### ISSUE THREAD

**Issue by flynneva** [RobotWebTools/rosbridge_suite#696]
**Description**

- Library Version: `ros2` branch compiled from source
- ROS Version: `rolling`
- Platform / OS: Intel x86_64 Ubuntu 20.04

**Steps To Reproduce**
- install ros 2 rolling from binaries
- install  [example pointcloud publisher](https://index.ros.org/p/examples_rclpy_pointcloud_publisher/#rolling) `sudo apt install ros-rolling-examples-rclpy-pointcloud-publisher`
- compile `rosbridge_server` from source & source installation
- `ros2 run examples_rclpy_pointcloud_publisher pointcloud_publisher`
- `ros2 run rosbridge_server rosbrigdge_websocket`
- connect via websocket using Foxglove studio

**Expected Behavior**

- connect fine, no errors, topcis listed in Foxglove and can visualize pointcloud

**Actual Behavior**

- errors are printed from `rosbridge_server rosbridge_websocket`:

```
InvalidServiceException: Service /rosapi/topics_and_raw_types does not exist
```

**Comment by jtbandes** [comment]
This is expected, you need to `ros2 launch rosbridge_server rosbridge_websocket_launch.xml`.
