### ISSUE TITLE
Websocket roslaunch launches rosapi twice

### ISSUE THREAD

**Issue by mhl787156** [RobotWebTools/rosbridge_suite#704]
**Description**

Hi, I have stumbled across an odd bug where when I try to launch `ros2 launch rosbridge_server rosbridge_websocket_launch.xml`, it launches two rosnodes named `rosapi` and thus throws a warning. It hasn't caused any problems until now where (I think) it is interferring with my connection to Foxglove:

Launch file:
```
root@f0667d79a4bd:/# ros2 launch rosbridge_server rosbridge_websocket_launch.xml 
[INFO] [launch]: All log files can be found below /root/.ros/log/2022-01-20-11-04-39-032547-f0667d79a4bd-40
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [rosbridge_websocket-1]: process started with pid [42]
[INFO] [rosapi_node-2]: process started with pid [44]
[rosapi_node-2] [WARN] [1642676679.322604700] [rcl.logging_rosout]: Publisher already registered for provided node name. If this is due to multiple nodes with the same name then all logs for that logger name will go out over the existing publisher. As soon as any node with that name is destructed it will unregister the publisher, preventing any further logs for that name from being published on the rosout topic.
[rosbridge_websocket-1] [INFO] [1642676679.338517200] [rosbridge_websocket]: Rosbridge WebSocket server started on port 9090
[rosbridge_websocket-1] [INFO] [1642676680.439530400] [rosbridge_websocket]: Client connected. 1 clients total.
```
Checking nodes:
```
root@7c665ff25d17:/ros_ws# ros2 node list
WARNING: Be aware that are nodes in the graph that share an exact name, this can have unintended side effects.
/rosapi
/rosapi
/rosbridge_websocket
```

The only place I've found reference to this is in this old post: https://answers.ros.org/question/344141/ros2-launch-creates-two-nodes-of-same-type/ and also this issue: https://github.com/ros2/launch/issues/411 which links to this issue https://github.com/ros2/geometry2/issues/124 

As mentioned in those posts, removing the `name=rosapi` field of the rosapi node entry within the launchfile appears to solve this problem (locally for me). 

i.e. from:
```
 <node name="rosapi" pkg="rosapi" exec="rosapi_node">
    <param name="topics_glob" value="$(var topics_glob)"/>
    <param name="services_glob" value="$(var services_glob)"/>
    <param name="params_glob" value="$(var params_glob)"/>
  </node>
```
to
```
  <node pkg="rosapi" exec="rosapi_node">
    <param name="topics_glob" value="$(var topics_glob)"/>
    <param name="services_glob" value="$(var services_glob)"/>
    <param name="params_glob" value="$(var params_glob)"/>
  </node>
```

Hopefully this isn't just me, but apologies if I've done something wrong in the setup! 

- Library Version: latest? not sure how to check! 
- ROS Version: Foxy
- Platform / OS: Ubuntu 20.04 (via latest docker container)

**Steps To Reproduce**

Running
```
ros2 launch rosbridge_server rosbridge_websocket_launch.xml
```
then checking the active nodes using `ros2 node list`

**Expected Behavior**
Ros launching the file will start a single rosapi node and the websocket node, I guess it should show as creating two nodes, `rosapi` and `rosapi_params`

**Actual Behavior**
Ros launching thefile creates two nodes named `rosapi` and ros therefore throws warnings.

**Comment by rob-clarke** [comment]
I've had a look and it seems to be in the `params.init()` call. I suspect the call to `rclpy.create_node` in [`params.py:73`](https://github.com/RobotWebTools/rosbridge_suite/blob/53985885a824c25846bef58d67adf99d6647ac57/rosapi/src/rosapi/params.py#L73) is picking up the node name remap from the arguments passed to the main `rosapi` script.

**Comment by rob-clarke** [comment]
Minimal repro:

```sh
ros2 run rosapi rosapi_node --ros-args --remap __node:=foo
```

NB: Name doesn't matter, even `rosapi` can be used and will cause issue.

This is related: https://answers.ros.org/question/316870/ros2-composition-and-node-names-with-launch-files/

Ugly fix is to replace [params.py:73](https://github.com/RobotWebTools/rosbridge_suite/blob/53985885a824c25846bef58d67adf99d6647ac57/rosapi/src/rosapi/params.py#L73) with:
```py
_node = rclpy.create_node(f"{parent_node_name.split('/')[-1]}_params",use_global_arguments=False)
```

**Comment by rob-clarke** [comment]
Actual fix would likely be to actually remove the parameters sub-node as suggested in the comment above that line.

**Comment by jtbandes** [comment]
It seems that the name collision happens in Galactic too, but that in Galactic it doesn't break the ability to call services on the rosapi node.

**Comment by jtbandes** [comment]
@rob-clarke I actually like the `use_global_arguments=False` idea. This doesn't seem ugly to me — it seems like a fix that directly addresses the problem. Refactoring per the comment might be better but probably more likely to cause new bugs unless a lot of effort is put in to adding comprehensive tests at the same time.

Why did you change the  name to `f"{parent_node_name.split('/')[-1]}_params"` in your proposed fix?

If you'd like to submit a PR with this fix that would be great.

**Comment by rob-clarke** [comment]
PR is up. Modified slightly to keep global arguments but explicitly overwrite the name. Subnode name is set to the same as the parent node but with a `_params` suffix to enable multiple instances of the bridge to run.
