### ISSUE TITLE
rosapi node is still alive while the service server inside won't response

### ISSUE THREAD

**Issue by jim1949** [RobotWebTools/rosbridge_suite#705]
hi, we are working with the official rosapi node(version is indigo:https://github.com/RobotWebToo...)

2.rosservice call .../get_param, and we cannot tab the consequent information and the terminal shows cannot conncet to it.

[Guess] Something stuck in the service callback function in the rosapi, but we are not sure. And have no idea how to move on the find the real reason.

**Comment by achim-k** [comment]
@jim1949 is this issue still relevant? Could you provide more information e.g. how to reproduce this issue?
