### ISSUE TITLE
Broken CI

### ISSUE THREAD

**Issue by MatthijsBurgh** [RobotWebTools/rosbridge_suite#725]
CI is broken because ROS2 rolling has migrated to Ubuntu 22.04 (Jammy). See https://github.com/ros/rosdistro/commit/0827daacdc5b4fc46d07e81bff448b2c909b8e9f

As Ubuntu 22.04 is not yet available for GH actions. The CI will stay broken until Ubuntu 22.04 is available.

**Comment by TheEppicJR** [comment]
The beta of 22.04 for GH actions is available now. https://github.com/actions/virtual-environments/issues/5490 Will this work or do yall intend to wait for the stable release?
