### ISSUE TITLE
rosbridge websocket slow down and hang 

### ISSUE THREAD

**Issue by MomoHsieh** [RobotWebTools/rosbridge_suite#765]
**Description**
Using rosbridge websocket slow down and hang when web opened about half an hour, but after re-launch the node and refresh website it will turn to normally.

- Library Version: 0.11.13
- ROS Version: noetic
- Platform / OS: Arm64 / Ubuntu (docker)  with Nvidia Jetson NX/AGX

**Steps To Reproduce**

We use websocket to send images, pointcloud, text... etc. to web, and it seems work well at start, but after half an hour, the web site UI and component updated slowly and to stuck, but the other node still running.

When I re-launch the websocket and website, it can be back to normally speed.

Memory and CPU loading under 50%, and didn't run to the maximum to let whole ros dead.

rosbridge websocket node will not dead but not response. Max bandwidth about trans data is 20M/s by one website.

Is there anything config I can change or notice?

**Comment by achim-k** [comment]
Are you sure that this is not an issue on the client side (your website)? E.g. it might be that you continuously add elements to the DOM which are not cleaned up properly.
