### ISSUE TITLE
CPU & Memory usage increases over time.

### ISSUE THREAD

**Issue by obi-t4** [RobotWebTools/rosbridge_suite#772]
**Description**

CPU & Memory usage increases over time.

- Library Version:
  installed with apt
  `ros-galactic-rosbridge-suite/focal,now 1.2.0-1focal.20220520.223734 amd64 [installed]`
- ROS Version:
  galactic
- Platform / OS:
  Ubuntu20.04

**Steps To Reproduce**

1. `ros2 run demo_nodes_cpp add_two_ints_server`
   https://github.com/ros2/demos is used.
1. `ros2 run rosbridge_server rosbridge_websocket`
2. Run the following scripts in multiple terminals: (two terminals are OK)
```python3
import roslibpy
import time
import datetime
import sys
from threading import Thread, Lock

ros = roslibpy.Ros(host='localhost', port=9090)
ros.run(timeout=None)

srv = roslibpy.Service(ros, "/add_two_ints", "example_interfaces/srv/AddTwoInts")
srvreq = roslibpy.ServiceRequest({"a": 1, "b": 2})

def srvcb(data):
    print(data)

def srv_errcb(data):
    print(f"error: {data}")

def service():
    while ros.is_connected:
        srv.call(srvreq, callback=srvcb, errback=srv_errcb, timeout=5)
        time.sleep(0.001)

th = Thread(target=service, daemon=True)
th.start()

while True:
    time.sleep(1)
```
1. wait for several hours. 4 or 5 hours.
2. In the beginning, CPU usage is about 45%, but after a few hours, it will exceed 50%~70%, in my environment.

**Expected Behavior**

CPU usage should keep up.

**Actual Behavior**

CPU usage increases slightly over time.

**Comment by obi-t4** [comment]
CPU usage increases up to 85%.
I found that memory usage is also increasing.
At the beginning RES(=Resident) is 400MB, but after 7 hours is 5GB.
![Screenshot from 2022-08-03 14-51-14](https://user-images.githubusercontent.com/58019445/182534505-e5634122-83ef-4fa0-830c-10b10a2b7579.png)

**Comment by lroop** [comment]
I also observe this issue, and see it slow down other ROS nodes in my system.

**Comment by Mechazo11** [comment]
Hi @obi-t4 I know this issue was probably closed but recently we saw this issue with a robotics system we are working with where the ROS 2 server is configured to send costmap and other pertinent data to foxglove via rosbridge_websocket. The RAM usage is stable but after around 15 min mark, the RAM usage gradually creeps up until all available memory is used up. Any suggestion on how to go about fixing this issue?

**Comment by simonbogh** [comment]
@Mechazo11 we experience the same with rosbridge on humble. rosbridge will use up all system memory until our docker crashes because of out of memory. This goes especially fast when we stream camera data.

**Comment by Mechazo11** [comment]
Hi @simonbogh thanks for the info. While this was quite back, I ended up moving the robot's visualzation assets to RVIZ with direct topic subscription via CycloneDDS. That solved both memory and CPU overheating issue due to saturation to 100%
