### ISSUE TITLE
Exception calling subscribe callback in ros2 galactic

### ISSUE THREAD

**Issue by robpinillos** [RobotWebTools/rosbridge_suite#779]
I am trying to run ros2djs sample to display a map on a html page. However when the open the html page rosbridge_server says

[ERROR] [1648211787.790774020] [rosbridge_websocket]: Exception calling subscribe callback: a bytes-like object is required, not 'str'

- ROS Version: ros2 galactic
- Platform / OS: Ubuntu 20.04

**Comment by jtbandes** [comment]
This ticket doesn't have enough information, can you provide steps to reproduce and/or the code you used?

**Comment by vela-io** [comment]
do you have any solution for this issue? @robpinillos
