### ISSUE TITLE
Unable To Import Custom Msg From Custom Package

### ISSUE THREAD

**Issue by CrawlerWheel** [RobotWebTools/rosbridge_suite#818]
**Description**
Hi, Authors.I define a custom message. As shown in the figure, I can get the message structure in ros, after modify the env var.
![image](https://user-images.githubusercontent.com/98396524/196587630-19d85d9d-8f0b-4707-962a-a531c1792da3.png)
But,when I use distant js program in Windows to subscribe rostopic `opencv_test/TargetArray` via rosbridge in Ubuntu, rosbridge alert:
![image](https://user-images.githubusercontent.com/98396524/196591924-570ee14e-fa2f-48e8-9f8b-d4499e6d7c8e.png)
It seems like that rosbridge can locate my custom package in Ubuntu. But, why its goal is to find  `opencv_test.msg`? Actually，this right goal is to find `TargetArray.msg`, just like ROS do.This is confusing to me！

- Library Version:ros-melodic-rosbridge-library/bionic,now 0.11.14-1bionic.20220615.170004 arm64
- ROS Version: Melodic
- Platform / OS: Ubuntu18.04

**Steps To Reproduce**
js code:
```js
const ROSLIB = require('roslib')
const eventemitter2 = require('eventemitter2')

// Connecting to ROS
var ros = new ROSLIB.Ros({
  url : 'ws://192.168.0.40:9090'
});

// If there is an error on the backend, an 'error' emit will be emitted.
ros.on('error', function(error) {
  console.log(error);
});

// Find out exactly when we made a connection.
ros.on('connection', function() {
  console.log('Connection made!');
});

ros.on('close', function() {
  console.log('Connection closed.');

});

// Create a connection to the rosbridge WebSocket server.
ros.connect('ws://192.168.0.40:9090');

var listener_mark = new ROSLIB.Topic({
  ros : ros,
  name : '/detect/MarkInfo',
  messageType : 'opencv_test/TargetArray'
});

listener_mark.subscribe(function(message) {
  console.log("gei it")
  //console.log('Received message on ' + listener.name +  "time: "+JSON.stringify(message.header.stamp));
  // If desired, we can unsubscribe from the topic as well.
  //listener.unsubscribe();
});
```
and output at terminal in js program :
![image](https://user-images.githubusercontent.com/98396524/196592666-8329c13b-ecc7-40e9-a4e8-226e49debb1d.png)

**Expected Behavior**
I wana it can let distant js program subscribe rostopic `opencv_test/TargetArray` ，and parse  `opencv_test/TargetArray` message successfully.

**Actual Behavior**
distant js program can`t get anything.

**Comment by achim-k** [comment]
Is the ROS environment loaded (usually via `source devel/setup.bash`) in the terminal in which you launch `rosbridge_server`?

If it's loaded, can you confirm that the following succeeds:
```bash
rosmsg show opencv_test/TargetArray
python -c 'from opencv_test.msg import TargetArray'
```

**Comment by CrawlerWheel** [comment]
Yes，I loaded, I have added `export ROS_PACKAGE_PATH=${ROS_PACKAGE_PATH}:/home/wheeltec/vins_ws/src` to .bashrc. And command `rosmsg show opencv_test/TargetArray` can return the message structure successfully.
![image](https://user-images.githubusercontent.com/98396524/196836242-258f7736-5369-40da-b99b-49addc57c8da.png)
![image](https://user-images.githubusercontent.com/98396524/196836941-dc3c5795-0ed4-49d4-a54f-9be05e0c7736.png)

**Comment by CrawlerWheel** [comment]
I restart the entire program just now，and js program can receive and parse message from this topic successfully.
I just suspended ubuntu in VM and turned off the Windows without any modification at night yesterday.
It`s so strange! But everything is ok now! Thank you！

**Comment by achim-k** [comment]
OK good to know it's working now. Closing this issue then.
