### ISSUE TITLE
No tag 0.11.16 on branch ros1

### ISSUE THREAD

**Issue by ribes4** [RobotWebTools/rosbridge_suite#826]
I just noticed that the tag [0.11.16](https://github.com/RobotWebTools/rosbridge_suite/tree/0.11.16) does not point to any commit of the [ros1](https://github.com/RobotWebTools/rosbridge_suite/tree/ros1) branch.

![image](https://user-images.githubusercontent.com/22292439/202700466-6f176ee7-3c3f-44f3-939d-05fd6d231b93.png)
![image](https://user-images.githubusercontent.com/22292439/202701518-b212d571-478c-4143-b154-03455f7dbb17.png)

I suggest that the tag should point to the commit  
[b0d0d711931d8ab7a5f079f948ced8875b4dc5d9](https://github.com/RobotWebTools/rosbridge_suite/commit/b0d0d711931d8ab7a5f079f948ced8875b4dc5d9) to keep track of changes in the ros1 branch.

**Comment by achim-k** [comment]
Thanks for noticing. I have updated the tag, could you confirm and then close this issue? Thanks!
