### ISSUE TITLE
when send action goal , gets an error and tried to find action interface in the msg packages

### ISSUE THREAD

**Issue by Cra2yQi** [RobotWebTools/rosbridge_suite#903]
**Description**

- Library Version: ros2
- ROS Version: humble
- Platform / OS: MacOs / ubuntu22.04

**Steps To Reproduce**

when i use roslibjs to send a action goal ，rosbridge-suit gets an error and tried to find action interface in the msg packages.

  ```javascript
action(serverName, actionName, argument) {
    const rosAction = new ROSLIB.ActionClient({
      ros: this.ros,
      serverName: serverName,
      actionName: actionName
    })
    const goal = new ROSLIB.Goal({
      actionClient: rosAction,
      goalMessage: argument
    });
    // Print out their output into the terminal.
    goal.on('feedback', function (feedback) {
      console.log('Feedback: ' + feedback.sequence);
    });
    goal.on('result', function (result) {
      console.log('Final Result: ' + result.sequence);
    });

    goal.send()
  }
```
<img width="1206" alt="image" src="https://github.com/RobotWebTools/rosbridge_suite/assets/59526112/849babfc-a5b8-4ee6-ab97-3a30534dbfa6">

**And I tried to use python to send the action, and I got the same error**

```python
import roslibpy
import roslibpy.actionlib
import time

def feedback_callback(feedback):
    print('Feedback received: ', feedback['sequence'])

def result_callback(result):
    print('Result received: ', result['sequence'])

def call_fibonacci_action(order):
    client = roslibpy.Ros(host='10.211.55.5', port=9090)
    client.run()

    action_client = roslibpy.actionlib.ActionClient(client, '/fibonacci', 'actionlib_tutorials/Fibonacci')

    goal = roslibpy.actionlib.Goal(action_client, roslibpy.Message({'order': order}))

    goal.on('feedback', feedback_callback)
    goal.on('result', result_callback)

    print('Sending goal...')
    goal.send()

    # 等待结果
    while not goal.is_finished:
        time.sleep(1)

    print('Goal processing done.')
    client.terminate()

if __name__ == '__main__':
    call_fibonacci_action(5)
```
<img width="1199" alt="image" src="https://github.com/RobotWebTools/rosbridge_suite/assets/59526112/9bfde436-ac13-4fc8-9170-a45b691b1314">

**Comment by sea-bass** [comment]
ROS 2 action support was added recently to `rosbridge_suite` in https://github.com/RobotWebTools/rosbridge_suite/pull/886. and is only implemented in `roslibjs`, not `roslibpy` yet.

The APIs you are using are the ones that work in ROS 1, where indeed the `.msg` namespace is searched to publish to the action's hidden topics.

**Comment by sea-bass** [comment]
Oh, the `roslibjs` example that does work in ROS 2 is here: https://github.com/RobotWebTools/roslibjs/blob/develop/examples/ros2_action_client.html

**Comment by sea-bass** [comment]
I've also created the underlying issue for `roslibpy` here: https://github.com/gramaziokohler/roslibpy/issues/122

So will go ahead and close this one, if that's okay.
