### ISSUE TITLE
ImportError: cannot import name 'get_parameter_value' from 'ros2param.api'

### ISSUE THREAD

**Issue by KubaArrow** [RobotWebTools/rosbridge_suite#970]
**Description**

In the latest version of the `rosapi` package, there is an issue with the `params.py` file where the function `get_parameter_value` from `ros2param.api` is no longer available in the Rolling distribution of ROS 2. It appears that the function name has changed to `get_value()` in the latest Rolling release. This causes the `rosapi_node` to fail with an import error when launching the `rosbridge_websocket` service.

- Library Version: Latest version (Rolling and ros2 branches)
- ROS Version: Rolling
- Platform / OS: Ubuntu 24.04

**Steps To Reproduce**

1. Install `rosbridge_server` and `rosapi` packages on ROS 2 Rolling.
2. Launch the rosbridge server using the following command:

```bash
ros2 launch rosbridge_server rosbridge_websocket_launch.xml
```

3. Observe the error related to `get_parameter_value` in the console.

**Expected Behavior**

The `rosapi_node` should launch correctly without import errors, and the `rosbridge_websocket` should start without issues.

**Actual Behavior**

The following error occurs:

```
ImportError: cannot import name 'get_parameter_value' from 'ros2param.api' (/opt/ros/rolling/lib/python3.12/site-packages/ros2param/api/__init__.py)
```

Changing the function call to `get_value()` in `params.py` resolves the issue and allows the `rosbridge_websocket` service to start as expected.

**Comment by bjsowa** [comment]
This was already fixed in #932 and is included in version `2.1.0` of rosbridge_suite which was released a couple of days ago.
